### ISSUE TITLE
On Migrating 

### ISSUE THREAD

**Issue by asmeyb** [TimothyMee/RMS#2]
In Connection.php line 664:

  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that correspond
  s to your MariaDB server version for the right syntax to use near 'json not null, `deleted_at` timestamp null, `created_at` ti
  mestamp null, `update' at line 1 (SQL: create table `courses_registered` (`id` int unsigned not null auto_increment primary ke
  y, `student_id` int not null, `semester` varchar(191) not null, `year` varchar(191) not null, `courses` json not null, `delete
  d_at` timestamp null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate utf8mb4_
  unicode_ci)

In Connection.php line 452:

  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that correspond
  s to your MariaDB server version for the right syntax to use near 'json not null, `deleted_at` timestamp null, `created_at` ti
  mestamp null, `update' at line 1

Asmeby@ASMEYB MINGW64 /c/xampp/htdocs/RMS (master)
$ php artisan migrate:refresh
Rolling back: 2018_01_14_121934_create_courses_table
Rolled back:  2018_01_14_121934_create_courses_table
Rolling back: 2018_01_14_121854_create_students_table
Rolled back:  2018_01_14_121854_create_students_table
Rolling back: 2014_10_12_100000_create_password_resets_table
Rolled back:  2014_10_12_100000_create_password_resets_table
Rolling back: 2014_10_12_000000_create_users_table
Rolled back:  2014_10_12_000000_create_users_table

In Connection.php line 664:

  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that correspond
  s to your MariaDB server version for the right syntax to use near 'json not null, `deleted_at` timestamp null, `created_at` ti
  mestamp null, `update' at line 1 (SQL: create table `courses_registered` (`id` int unsigned not null auto_increment primary ke
  y, `student_id` int not null, `semester` varchar(191) not null, `year` varchar(191) not null, `courses` json not null, `delete
  d_at` timestamp null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate utf8mb4_
  unicode_ci)

In Connection.php line 452:

  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that correspond
  s to your MariaDB server version for the right syntax to use near 'json not null, `deleted_at` timestamp null, `created_at` ti
  mestamp null, `update' at line 1

**Comment by TimothyMee** [comment]
This error shows that your MariaDB version is old and doesn't support the use of 'Json' type.
Just upgrade your MariaDB or change the data type in the migration from 'Json' to 'String' and you should be good

**Comment by ciraj8** [comment]
Sign in problem with administrator privileges
